spring.application.name=event.booking

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}?sslmode=disable&options=-c%20TimeZone%3DUTC
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.deserialization.fail-on-unknown-properties=true


# Server Configuration
server.port=${PORT:8080}
